name: huystore
description: "App quản lý cửa hàng dịch vụ Lalalab."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ^3.9.0
 
dependencies:
  flutter: 
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0  
  firebase_auth: 6.0.1
  mobile_scanner: 7.0.1
  cupertino_icons: ^1.0.8  
  firebase_core: ^4.0.0 
  firebase_messaging: ^16.0.0 
  badges: ^3.1.2
  provider: ^6.0.5
  dropdown_search: ^5.0.6
  intl: ^0.19.0
  qr_flutter: 4.1.0
  flutter_typeahead: ^5.2.0
  signalr_netcore: ^1.2.2 
  permission_handler: ^11.3.1  
  flutter_launcher_icons: "0.14.4" 
  flutter_lints: "6.0.0" 
  image_picker: ^1.0.8    
  image_gallery_saver_plus: ^4.0.1
  path_provider: ^2.1.2
  cached_network_image: ^3.3.0 
  url_launcher: ^6.1.10
  share_plus: ^7.2.2 
  esc_pos_utils_plus : ^2.0.4
  flutter_bluetooth_serial_plus: ^0.5.1    
  bluetooth_print_plus: ^2.4.6
  firebase_analytics: ^12.0.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter   

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"  
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/logo-store.png
    - assets/images/icon.png
    - lib/core/config/.env.development
    - lib/core/config/.env.production
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
